# Generated by Django 4.1.4 on 2023-02-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wormzatwar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('lobbyPK', models.CharField(editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
