# Generated by Django 4.1.4 on 2023-02-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wormzatwar', '0003_wormuser_lobby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wormuser',
            name='lobby',
        ),
        migrations.AddField(
            model_name='wormuser',
            name='lobby',
            field=models.ManyToManyField(to='wormzatwar.lobby'),
        ),
    ]
