# Generated by Django 4.1.4 on 2023-02-12 22:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wormzatwar', '0006_lobby_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='stage',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
    ]
